version: "3.3"
services:
  backend:
    build: .
    ports:
      - '3000:3000'      
 mysqldb:
    image: mysql:8.0.23
    networks:
      - docker_network
     environment:
      - MYSQL_DATABASE=carsdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Abc123456789
      
      
     
networks:
    default:
        external:
            name: docker_network
