version: "3"
services:
  backend:
    build: .
    image: backend
    container_name: backend
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ~/backend_data:/public/product-images
networks:
  default:
    external:
      name: docker_network
