version: "3.3"
services:
  backend:
    build: .
    ports:
      - '3000:3000'      
 mysqldb:
    image: mysql:8.0.23
    networks:
      - docker_network
     environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
     
networks:
    default:
        external:
            name: docker_network
